### ISSUE TITLE
Some things don't work for me

### ISSUE THREAD

**Issue by Adrianilloo** [Sarrus1/sourcepawn-vscode#22]
Hi,

First of all, I'd like to say that I recently found this and I feel that an extension for a popular and well-suited IDE such as VSCode is the way to go for SourcePawn integration, after having used other dedicated IDEs. So I fully support the idea.

I've noticed few essential functionality issues at least I have (version is `1.0.6`):

1. Members of untagged `enum`'s don't appear in autocompletion. The closest workaround is using an `enum _ { ... }`.
2. '**Go to Definition (F12)**' seems to fail for functions that either aren't marked `public` or whose name contains numbers
3. Autocompletion is almost completely blank when being on a secondary `.sp` file which is included by the main file (tried to configure the `Main_path` setting, pointing to the main `sp` file, but it failed)

If I find more issues I'd like to add them into this one. Let me know if that's fine.

Thanks.

**Comment by Sarrus1** [comment]
Hi,

Thanks you for your interest in the project.

1. The regex for an `enum` is `/^\s*(?:enum\s+)([A-z0-9_]*)/` as of **1.0.6**, which is why it doesn't detect untagged `enums`.
2. Functions which don't have `public`, `stock`, `forward` or `native` as a prefix are not supported at all for now, because it caused issues with the parser recognising function calls as function declaration.
3. AutoCompletion is organised by files under the hood, which explains why it's blank on another file, even when imported.

All of those issues will (hopefully) be fixed in the next release. They all come from me being beginner/intermidiate with SourcePawn, and therefore not knowing all the details of the language.

I really appreciate such feedback, because I wouldn't have caught those bugs otherwise, so please keep it coming 👍 

I also encourage you to come visit [this Discord server](https://discord.tensor.fr) to discuss the extension's development.

**Comment by Adrianilloo** [comment]
I understand. Thanks for the honest answer!

I will use the extension anyways 👍🏽

**Comment by Sarrus1** [comment]
Fixed all of the above issues in 1.11.0
