### ISSUE TITLE
Formatter doesn't work in .inc files

### ISSUE THREAD

**Issue by Nickelony** [Sarrus1/sourcepawn-vscode#265]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

It is not possible to Format .inc files. The option simply isn't there.

# To Reproduce

Try to format any .inc file.

# Expected behaviour

Be able to format a .inc file.

# Error messages

None.

**Comment by Sarrus1** [comment]
Hello,

This is actually "intended" because the formatter would often completely break .inc files, as clang-format does not understand methodmaps and structs.
https://github.com/Sarrus1/sourcepawn-vscode/blob/ce2ff29dee92dc49dc9901e2a076f37406e829af/src/spIndex.ts#L175

I would advise you to use https://github.com/Sarrus1/spformat instead, which I am planning to implement into the extension anyway.

**Comment by Sarrus1** [comment]
Allowed the formatting of .inc files in v5.
