### ISSUE TITLE
Performance problems occur during usage. Memory leaks

### ISSUE THREAD

**Issue by Boollan** [Sarrus1/sourcepawn-vscode#288]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** v1.76.1
- **Extension version:** v5.3.1

# Further Information

When the SP file is very complex and the size of the file exceeds 1MB, the memory usage is large and the system running memory leakage is affected

# To Reproduce

# Code to reproduce the behaviour

Unable to provide

# Expected behaviour

Private project, unable to provide code

# Error messages
There is no

**Comment by Sarrus1** [comment]
Hi, please see #252 as this has already been reported and is being fixed.

**TL;DR: Use the pre-release version for now**

There is a memory leak in the parser generator library which I cannot fix.
I'm almost done migrating the backend of the extension to Rust, and I have  already published some pre-release versions which fix the memory leak. Please try those as they are stable and almost ready for release (just a few misc features missing).

Closing because of duplicate.
