### ISSUE TITLE
"Go to definition" and hints stop working in .inc file.

### ISSUE THREAD

**Issue by stas11s11t** [Sarrus1/sourcepawn-vscode#353]
This happens quite often. To fix this I have to rename .inc file and restart vs code, but I still haven't figured out the exact sequence of steps I need to do to fix this. Very annoying. This seems to be related to ctrl+shift+f, when I want to rename the name of a function in several files. In any case, thanks for the extension, it is very good, but this flaw does not give me peace.

**Comment by Alienmario** [comment]
This happens quite often to me too. Restarting sourcepawn-lsp helps for a short while.

**Comment by stas11s11t** [comment]
> This happens quite often to me too. Restarting sourcepawn-lsp helps for a short while.

Restart sourcepawn-lsp does not help me, maybe you are doing something additional?

**Comment by Sarrus1** [comment]
Thanks for reporting this
I am actively developing this branch, which hopefully will fix the issue: https://github.com/Sarrus1/sourcepawn-vscode/tree/feat/salsa

**Comment by Sarrus1** [comment]
Hello, can anybody experimenting this issue can try the pre-release version to see if it still happens? Thanks!

**Comment by Alienmario** [comment]
@Sarrus1
No more goto-declaration issues for me!

Well, there some special cases.
- Goto Handle goes to `using __intrinsics__.Handle` rather than the `enum Handle`.
- Does not work for functions inside macros `#define TICK_INTERVAL	(GetTickInterval())`

---

I'll list some of my  unrelated findings of v7 below:
- Some settings are not migrating correctly - iirc "SourcePawnLanguageServer.compiler.path" and "SourcePawnLanguageServer.includeDirectories" (perhaps extra s in includes)
- I'm so used to having function docs popup, I find myself pressing a kb shortcut to 'Trigger Parameter Hints' which now does something unrelated since they are not available :(
- Pressing 'Show Definition Preview Hover' shortcut while having cursor at the last letter of a function name does nothing.
- Go to references is not yet finding any for me.
- Getting 'Request textDocument/semanticTokens/full failed.' on unsaved SP files.
- Getting 'Request textDocument/definition failed.' when ctrl-hovering over myinfo elements.
```
#include <sourcemod>

public Plugin myinfo =
{
	name = "test",
	author = "test",
	description = "test",
	version = "test",
	url = "test"
};
```

**Comment by Sarrus1** [comment]
Hey @Alienmario thank you for the feedback, this is very valuable, I will try to fix those bugs asap! Will report back here 👍

**Comment by Alienmario** [comment]
> Not that `Nor inside #if defined blocks it thinks are disabled.` will probably never fully work.

That's fine.
I guess my long term wish is more related to how preprocessor blocks are evaluated.

1) We can pass defines through compiler arguments, and even switch through compile environments with "sourcepawn.availableAPIs" with different arguments in each - that's very good. However I couldn't find a way to make it recognize that and enable the required code paths in editor.

2) Some stocks are written in a way that depend on other includes being included beforehand. I use this in my stock libraries, but could only find one instance in [SMLib](https://github.com/bcserv/smlib/blob/transitional_syntax/scripting/include/smlib/server.inc#L20). I suppose you can only control this if you know the main file. But as of right now, whether a particular block is enabled in editor is indeterminate.

**Comment by Sarrus1** [comment]
Some issues have been fixed and some have been triaged to other issues as I am trying to focus on roadblock issue for the upcoming stable release 👍 

All the details are in #391 

In the meantime, v7.2.8 includes all the latest fixes if you want to give it a go :)
