### ISSUE TITLE
[BUG] Go to definition on non Sourcemod_Home includes and Intellisense on non main files

### ISSUE THREAD

**Issue by aleeperezz16** [Sarrus1/sourcepawn-vscode#69]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.58.2]
* **Extension version:** [v1.12.7]

## Further Information

If I am on any file of the project and add a function from the "Optional include dir paths", the Go to definition doesn't take you to the file.

Also, if you are on any source file and it's not the main one, Intellisense breaks and doesn't show you the function parameters.
![image](https://user-images.githubusercontent.com/53284952/128402421-78edf492-dc00-4eea-a3cf-5aa714cea8a1.png)
![image](https://user-images.githubusercontent.com/53284952/128402460-0eb1bb31-8a34-4abe-b6a9-1628cd1f073b.png)

The first image is "IsClientInGame" native from Sourcemod Home path and the second one from Optional include dir paths "smlib" include file.

**Comment by Sarrus1** [comment]
> If I am on any file of the project and add a function from the "Optional include dir paths", the Go to definition doesn't take you to the file.

I wasn't able to replicate this. I used SteamWorks.inc and added it to my Desktop, added the path to my Desktop as an additionnal include directory and GoToDefinition worked properly. This is with v1.12.8 however, maybe I've fixed it without knowing, the code changed a lot between the two versions. Can you try with v1.12.8?

> Also, if you are on any source file and it's not the main one, Intellisense breaks and doesn't show you the function parameters.

This should be fixed in the commit below, I'll have to test this in details to make sure I don't break anything.

**Comment by aleeperezz16** [comment]
Alright, I will test it and get you noticed if it still happens

**Comment by aleeperezz16** [comment]
Works like a charm now, thanks.
Another thing I've now encountered is that some keywords (Action) and constants like enumerations (Plugin_Stop, Plugin_Continue) or defines (ADMFLAG_RESERVATION, etc.) now are not highlighted with colors. I've changed my theme cause' I thought it was a theme parsing problem but it also happens with Dark+ default VS Code theme. I saw you made some changes on includes and defines to make them look more like C++, so I think it comes from this hand.

**Comment by Sarrus1** [comment]
Oh right.
Before, built-in defines and enum members such as the one you mentionned where hardcoded into the extension, which is fine, but gets confusing when you add your own defines and enums
I want to make it so that they get highlighted programatically, so that nothing has to be hardcoded, hopefully I can figure out a way to make it fast enough so that the extension is still usable...
I'll see what I can do 👍

**Comment by aleeperezz16** [comment]
Sorry for keep on commenting this issue but now I've another error with Go to Definition.
If you try to do this with a define, it shows this error:
![image](https://user-images.githubusercontent.com/53284952/128434038-e5fc7c75-4672-4f63-bb37-b73698e740d7.png)

**Comment by Sarrus1** [comment]
No problem

Note for later, this comes from [here](https://github.com/Sarrus1/sourcepawn-vscode/blob/7bfd82412a6e1dbc233a4e43db8913d51a4e91de/client/src/Providers/spCompletions.ts#L167)
